# The main config file for your Jekyll template

# Site settings
title: Philosophy of Memory Organization               # used for the html title of every page
desc: >
  The Philosophy of Memory Organization (PhOMO) is an international organization that fosters interaction among philosophers interested in the study of memory and its relationship to other cognitive phenomena and philosophical issues. PhoMo meets every two years, each time in a new location. We invite contributions from all sub-fields of philosophy and stages of professional development.


url: http://jackal.com      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: phomo@gmx.com
author: PhOMO
twitter_username: 
github_username: 
github_source: 

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About
    url: /about/
    desc: About PhOMO
  - title: Works
    url: /works/
    desc: Works in Philosophy of Memory
  - title: Conferences
    url: /conferences/
    desc: Conferences
  - title: Pages
    url: /pages/
    desc: Pages
  
 
# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

